/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorTelefono;
import ec.edu.ups.controlador.ControladorUsuario;
import ec.edu.ups.dao.TelefonoDao;
import ec.edu.ups.dao.UsuarioDao;

/**
 *
 * @author Paul Idrovo
 */
public class VistaPrincipalApp extends javax.swing.JFrame {

    private VistaInicioSesion inicioSesion;
    private VistaDirectorioGeneral directorioGeneral;
    private TelefonoDao daoTelefono;
    private UsuarioDao daoUsuario;
    private ControladorTelefono controladorTelefono;
    private ControladorUsuario controladorUsuario;

    public VistaPrincipalApp() {
        initComponents();
        //CREAR DAO Y CONTROLADORES
        daoTelefono = new TelefonoDao();
        daoUsuario = new UsuarioDao();
        controladorTelefono = new ControladorTelefono(daoTelefono);
        controladorUsuario = new ControladorUsuario(daoUsuario, daoTelefono);
        
        //CREAR VISTAS
        inicioSesion = new VistaInicioSesion(mnAgregarTelefono, mnEditarTelefono, mnMisTelefonos, mnIniciarSesion, mnSalir,  mnRegistrarse, controladorUsuario, controladorTelefono);
        directorioGeneral = new VistaDirectorioGeneral(controladorUsuario, controladorTelefono);
        desktopPane.add(inicioSesion);
        desktopPane.add(directorioGeneral);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mnIniciarSesion = new javax.swing.JMenuItem();
        mnRegistrarse = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        mnDirectorioGeneral = new javax.swing.JMenuItem();
        mnAgregarTelefono = new javax.swing.JMenuItem();
        mnEditarTelefono = new javax.swing.JMenuItem();
        mnMisTelefonos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DIRECTORIO TELEFONICO");

        desktopPane.setBackground(new java.awt.Color(248, 189, 152));
        desktopPane.setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));

        menuBar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/iconos/power.png"))); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("INICIO");

        mnIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/iconos/usuario (1).png"))); // NOI18N
        mnIniciarSesion.setMnemonic('o');
        mnIniciarSesion.setText("Iniciar Sesion");
        mnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIniciarSesionActionPerformed(evt);
            }
        });
        fileMenu.add(mnIniciarSesion);

        mnRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/iconos/anadir.png"))); // NOI18N
        mnRegistrarse.setMnemonic('s');
        mnRegistrarse.setText("Registrarse");
        mnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRegistrarseActionPerformed(evt);
            }
        });
        fileMenu.add(mnRegistrarse);

        mnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/iconos/cerrar-sesion.png"))); // NOI18N
        mnSalir.setMnemonic('s');
        mnSalir.setText("Salir");
        mnSalir.setEnabled(false);
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        fileMenu.add(mnSalir);

        menuBar.add(fileMenu);

        editMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/iconos/directorio.png"))); // NOI18N
        editMenu.setMnemonic('e');
        editMenu.setText("MENU DIRECTORIO");

        mnDirectorioGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/iconos/agenda.png"))); // NOI18N
        mnDirectorioGeneral.setMnemonic('t');
        mnDirectorioGeneral.setText("Directorio General");
        mnDirectorioGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDirectorioGeneralActionPerformed(evt);
            }
        });
        editMenu.add(mnDirectorioGeneral);

        mnAgregarTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/iconos/anadir (1).png"))); // NOI18N
        mnAgregarTelefono.setMnemonic('y');
        mnAgregarTelefono.setText("Agregar Telefono");
        mnAgregarTelefono.setEnabled(false);
        mnAgregarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAgregarTelefonoActionPerformed(evt);
            }
        });
        editMenu.add(mnAgregarTelefono);

        mnEditarTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/iconos/editar-telefono.png"))); // NOI18N
        mnEditarTelefono.setMnemonic('p');
        mnEditarTelefono.setText("Editar Telefono");
        mnEditarTelefono.setEnabled(false);
        editMenu.add(mnEditarTelefono);

        mnMisTelefonos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/iconos/directorio-telefonico.png"))); // NOI18N
        mnMisTelefonos.setMnemonic('d');
        mnMisTelefonos.setText("Ver mis telefonos");
        mnMisTelefonos.setEnabled(false);
        editMenu.add(mnMisTelefonos);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIniciarSesionActionPerformed
        inicioSesion.setVisible(true);        
    }//GEN-LAST:event_mnIniciarSesionActionPerformed

    private void mnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRegistrarseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnRegistrarseActionPerformed

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        mnAgregarTelefono.setEnabled(false);
        mnEditarTelefono.setEnabled(false);
        mnMisTelefonos.setEnabled(false);
        mnSalir.setEnabled(false);
        mnIniciarSesion.setEnabled(true);
        mnRegistrarse.setEnabled(true);
        desktopPane.removeAll();
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mnAgregarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAgregarTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnAgregarTelefonoActionPerformed

    private void mnDirectorioGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDirectorioGeneralActionPerformed
        directorioGeneral.setVisible(true);
    }//GEN-LAST:event_mnDirectorioGeneralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipalApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipalApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipalApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipalApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipalApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnAgregarTelefono;
    private javax.swing.JMenuItem mnDirectorioGeneral;
    private javax.swing.JMenuItem mnEditarTelefono;
    private javax.swing.JMenuItem mnIniciarSesion;
    private javax.swing.JMenuItem mnMisTelefonos;
    private javax.swing.JMenuItem mnRegistrarse;
    private javax.swing.JMenuItem mnSalir;
    // End of variables declaration//GEN-END:variables

}
